#!/bin/sh -e
for file in *; do
    if [ "$file" != "install" ]; then
        src="$PWD/$file"
        dest="$HOME/.$file"
        if [ -h "$dest" ]; then
            rm "$dest"
        fi
        echo Linking: $src '=>' $dest 
        ln -s "$src" "$dest"
    fi
done
